# Generated by Django 3.1.6 on 2021-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('postal_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=250)),
                ('linkedin_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('personal_website', models.URLField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('last_modified_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
