# Generated by Django 3.1.6 on 2021-02-16 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('personal_website', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 2, 16, 6, 45, 25, 429739, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
