# Generated by Django 3.1.6 on 2021-02-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_modified_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
