# Generated by Django 3.1.6 on 2021-02-15 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210214_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_modified_on',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 15, 1, 31, 24, 40892, tzinfo=utc)),
        ),
    ]
