# Generated by Django 3.1.6 on 2021-02-15 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210215_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_modified_on',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 2, 15, 1, 32, 36, 154967, tzinfo=utc)),
        ),
    ]
