# Generated by Django 3.1.6 on 2021-02-15 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210215_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_modified_on',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 2, 15, 1, 44, 8, 284553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='personal_website',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
