# Generated by Django 3.1.6 on 2021-02-15 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210215_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_modified_on',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2021, 2, 15, 2, 37, 20, 964155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
